version: "3.7"
services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    image: php
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html/:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - php_services

  mysql:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - 3306:3306
    networks:
      - php_services

networks:
  php_services:
    driver: bridge